### ISSUE TITLE
Limit The Maximum and Minimal Happiness

### ISSUE THREAD

**Issue by diegoseso** [diegoseso/tamagochi#5]
We have to create a limitation on the Happiness measurement bar, to achieve this we need to: 

Create a limiter for the Maximum , if a pet or feed action occurs and the actual happiness results into more than the maximumHappiness then the happiness should be the maximumHappiness.

Create a limiter for the Minimum happiness that a user can have , if a nag action occurs and the actual happiness results into less than the minimumHappiness then the happiness should be 0

**Comment by SqueakingJojokes** [comment]
This issue has been done.

We implemented code so actualHappiness can't be less than 0 or more than 100.
